export const columns = [
  {
    field: "name",
    headerName: "Name",
    editable: true,
    headerAlign: "center",
    align: "center",
    flex: 2,
    headerClassName: "expense-grid-header",
  },
  {
    field: "amount",
    headerName: "Amount",
    type: "number",
    editable: true,
    headerAlign: "center",
    align: "center",
    flex: 1,
    headerClassName: "expense-grid-header",
  },
  {
    field: "category",
    headerName: "Category",
    editable: true,
    headerAlign: "center",
    align: "center",
    flex: 2,
    headerClassName: "expense-grid-header",
  },
  {
    field: "createdDate",
    headerName: "Date Created",
    type: "date",
    editable: true,
    headerAlign: "center",
    align: "center",
    flex: 2,
    headerClassName: "expense-grid-header",
    valueGetter: (params) => new Date(params.row.createdDate),
  },
];
