export const EXPENSE_ADD_REQUEST = "EXPENSE_ADD_REQUEST";
export const EXPENSE_ADD_SUCCESS = "EXPENSE_ADD_SUCCESS";
export const EXPENSE_ADD_FAIL = "EXPENSE_ADD_FAIL";

export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST";
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_FAIL = "GET_EXPENSE_FAIL";
